import { getSubjectName, formatTime } from "./helpers";

export function downloadBlob(content: string, filename: string, contentType: string) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportSessionCSV(sessionLog: any[], subjects: any[]) {
  let csv = "ID,Date,Subject,Duration (secs),Time Format,Notes\n";
  sessionLog.forEach((entry) => {
    const subjName = getSubjectName(entry.subjId, subjects);
    const date = entry.date || "";
    const secs = entry.secs || 0;
    const formatted = formatTime(secs);
    const notesStr = entry.notes ? `"${entry.notes.replace(/"/g, '""')}"` : '""';
    csv += `${entry.id},${date},"${subjName}",${secs},${formatted},${notesStr}\n`;
  });
  downloadBlob(csv, "arkmaester-session-log.csv", "text/csv;charset=utf-8;");
}

export function exportSessionTxt(entry: any, subjects: any[]) {
  const subjName = getSubjectName(entry.subjId, subjects);
  const text = `
========================================
       Arkmaester Session Report
========================================
ID:         ${entry.id}
Date:       ${entry.date}
Subject:    ${subjName}
Study Time: ${formatTime(entry.secs)} (${entry.secs} seconds)

Notes:
${entry.notes || "No notes recorded."}

----------------------------------------
Generated by Arkmaester — Conquer the Chaos. Settle the Score.
========================================
`;
  downloadBlob(text, `arkmaester-session-${entry.id}.txt`, "text/plain");
}

export function exportWeeklyReportTxt(sessionLog: any[], distractionLog: any[], streak: number, subjects: any[]) {
  let totalSecs = sessionLog.reduce((acc, s) => acc + s.secs, 0);
  let totalHrs = (totalSecs / 3600).toFixed(1);

  let subjectsBreakdown = "";
  subjects.forEach((sub) => {
    const subSecs = sessionLog.filter((s) => s.subjId === sub.id).reduce((acc, s) => acc + s.secs, 0);
    const subHrs = (subSecs / 3600).toFixed(1);
    subjectsBreakdown += ` - ${sub.name}: ${subHrs} hrs\n`;
  });

  const text = `
==============================================
       Arkmaester Weekly Report
==============================================
Generated: ${new Date().toLocaleDateString()}

PROGESS METRICS:
- Total Study Hours:   ${totalHrs} hrs
- Focus Days Streak:   ${streak} days
- Flagged Distractions: ${distractionLog.length} events

SUBJECT TIME BREAKDOWN:
${subjectsBreakdown || "No subject study sessions logged yet."}

STATUS COMMENTARY:
${totalSecs > 15 * 3600 ? "Arkmaester says: Excellent consistency! Your pace is stellar." : "Arkmaester recommends: Push for one extra Pomodoro session."}

----------------------------------------------
Generated ${new Date().toLocaleDateString()} by Arkmaester — Conquer structural layout
==============================================
`;
  downloadBlob(text, "arkmaester-weekly-report.txt", "text/plain");
}

// Generate premium HTML5 Canvas Image for social sharing
export function generateShareCard(canvasId: string, totalHrs: number, streak: number, dailyPct: number) {
  const canvas = document.getElementById(canvasId) as HTMLCanvasElement;
  if (!canvas) return;

  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  const W = 400;
  const H = 250;
  canvas.width = W;
  canvas.height = H;

  // Background gradient (Cosmic Slate style)
  const grad = ctx.createLinearGradient(0, 0, 0, H);
  grad.addColorStop(0, "#050810");
  grad.addColorStop(1, "#0d1424");
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, W, H);

  // Background cyber grids lines
  ctx.strokeStyle = "rgba(0, 229, 255, 0.05)";
  ctx.lineWidth = 1;
  for (let i = 0; i < W; i += 20) {
    ctx.beginPath(); ctx.moveTo(i, 0); ctx.lineTo(i, H); ctx.stroke();
  }
  for (let i = 0; i < H; i += 20) {
    ctx.beginPath(); ctx.moveTo(0, i); ctx.lineTo(W, i); ctx.stroke();
  }

  // Draw Logo Branding
  ctx.font = "bold 15px sans-serif";
  ctx.fillStyle = "#00e5ff";
  ctx.fillText("ARK", 28, 36);
  ctx.fillStyle = "#e8edf8";
  ctx.fillText("MAESTER", 62, 36);

  ctx.font = "9px monospace";
  ctx.fillStyle = "#5a6a8a";
  ctx.fillText("// productivity OS", 28, 52);

  // Divide line
  ctx.strokeStyle = "#1a2540";
  ctx.beginPath(); ctx.moveTo(28, 65); ctx.lineTo(W - 28, 65); ctx.stroke();

  // Draw taglines
  ctx.font = "italic 11px sans-serif";
  ctx.fillStyle = "#a78bfa";
  ctx.fillText('"Conquer the Chaos. Settle the Score."', 28, 85);

  // Render Stats Grid
  const renderStat = (x: number, y: number, label: string, val: string, color: string) => {
    ctx.font = "24px monospace";
    ctx.fillStyle = color;
    ctx.fillText(val, x, y);

    ctx.font = "8px sans-serif";
    ctx.fillStyle = "#5a6a8a";
    ctx.fillText(label.toUpperCase(), x, y + 15);
  };

  renderStat(30, 140, "Total Study", `${totalHrs.toFixed(1)}H`, "#e8edf8");
  renderStat(150, 140, "Days Streak", `${streak}D`, "#00ff88");
  renderStat(270, 140, "Goal Pct", `${dailyPct}%`, "#00e5ff");

  // Footer credit
  ctx.font = "8px monospace";
  ctx.fillStyle = "#5a6a8a";
  ctx.fillText("Generated by Arkmaester · arkmaester.app", 28, H - 20);

  // Draw a subtle cyan neon bounding box
  ctx.strokeStyle = "rgba(0, 229, 255, 0.4)";
  ctx.lineWidth = 1;
  ctx.strokeRect(10, 10, W - 20, H - 20);
}

// Beautiful simple canvas confetti launcher (requires no external npm packs, fully reliable)
export function fireConfetti(options: { count: number }) {
  const canvas = document.getElementById("confetti-canvas") as HTMLCanvasElement;
  if (!canvas) return;

  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  const resize = () => {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
  };
  window.addEventListener("resize", resize);
  resize();

  interface Particle {
    x: number;
    y: number;
    r: number;
    color: string;
    vx: number;
    vy: number;
    rotation: number;
    rotSpeed: number;
  }

  const colors = ["#00e5ff", "#00ff88", "#ffb300", "#a78bfa", "#ff4444"];
  const particles: Particle[] = [];

  for (let i = 0; i < (options.count || 50); i++) {
    particles.push({
      x: canvas.width / 2,
      y: canvas.height + 20,
      r: Math.random() * 6 + 4,
      color: colors[Math.floor(Math.random() * colors.length)],
      vx: (Math.random() - 0.5) * 15,
      vy: -Math.random() * 20 - 10,
      rotation: Math.random() * 360,
      rotSpeed: (Math.random() - 0.5) * 10,
    });
  }

  let aniFrame: number;
  const draw = () => {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    let active = false;

    particles.forEach((p) => {
      p.x += p.vx;
      p.y += p.vy;
      p.vy += 0.55; // gravity
      p.vx *= 0.98; // wind resistance
      p.rotation += p.rotSpeed;

      if (p.y < canvas.height + 20) {
        active = true;
        ctx.save();
        ctx.translate(p.x, p.y);
        ctx.rotate((p.rotation * Math.PI) / 180);
        ctx.fillStyle = p.color;
        ctx.fillRect(-p.r, -p.r / 2, p.r * 2, p.r);
        ctx.restore();
      }
    });

    if (active) {
      aniFrame = requestAnimationFrame(draw);
    } else {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      window.removeEventListener("resize", resize);
    }
  };

  draw();
}
