// ── Export Utilities ──────────────────────────────────────────────────────

// ── CSV Session Log ───────────────────────────────────────────────────────
export function exportSessionCSV(sessionLog, subjects) {
  const escape = (v) => `"${String(v).replace(/"/g, '""')}"`;
  const header = ["Index","Date","Time","Subject","Duration(min)","Session Type","Notes"]
    .map(escape).join(",");
  const rows = sessionLog.map((e, i) => {
    const subj = subjects.find((s) => s.id === e.subjId);
    const d    = new Date(e.ts);
    return [
      escape(i + 1),
      escape(e.date),
      escape(d.toLocaleTimeString([], { hour:"2-digit", minute:"2-digit" })),
      escape(subj ? subj.name : "Untagged"),
      escape(Math.round(e.secs / 60)),
      escape("Pomodoro Focus"),
      escape(e.notes || ""),
    ].join(",");
  });
  const csv = [header, ...rows].join("\n");
  downloadBlob(new Blob([csv], { type:"text/csv" }), "arkmaester-session-log.csv");
}

// ── Session TXT Report ────────────────────────────────────────────────────
export function exportSessionTxt(entry, subjects) {
  const subj  = subjects.find((s) => s.id === entry.subjId);
  const mins  = Math.round(entry.secs / 60);
  const d     = new Date(entry.ts);
  const lines = [
    "═══════════════════════════════════",
    "       Arkmaester Session Report",
    "═══════════════════════════════════",
    `Subject         : ${subj ? subj.name : "Untagged"}`,
    `Duration        : ${mins} minutes`,
    `Date            : ${d.toLocaleDateString([], { weekday:"long", year:"numeric", month:"long", day:"numeric" })}`,
    `Time            : ${d.toLocaleTimeString([], { hour:"2-digit", minute:"2-digit" })}`,
    `Session type    : Pomodoro focus`,
    `Pomodoros today : ${entry.sessionIndex ?? 1}`,
    entry.notes ? `\nNotes:\n${entry.notes}` : "",
    "═══════════════════════════════════",
    "Generated by Arkmaester",
  ].join("\n");
  downloadBlob(new Blob([lines], { type:"text/plain" }), `arkmaester-session-${entry.id}.txt`);
}

// ── Weekly Report TXT ─────────────────────────────────────────────────────
export function exportWeeklyReportTxt(summary) {
  const lines = [
    "═══════════════════════════════════",
    "       Arkmaester Weekly Report",
    "═══════════════════════════════════",
    `Rating          : ${summary.rating}`,
    `Total Hours     : ${summary.totalHrs}h`,
    `Sessions        : ${summary.sessions}`,
    `Best Day        : ${summary.bestDay}`,
    `Top Subject     : ${summary.topSubject}`,
    `Streak          : ${summary.streak} days`,
    `Distractions    : ${summary.distractions}`,
    "",
    `AI Comment: ${summary.aiComment}`,
    "═══════════════════════════════════",
    `Generated ${new Date().toLocaleDateString()} by Arkmaester`,
  ].join("\n");
  downloadBlob(new Blob([lines], { type:"text/plain" }), `arkmaester-weekly-${Date.now()}.txt`);
}

// ── Share Card (Canvas PNG) ───────────────────────────────────────────────
export function generateShareCard({ totalSessions, streak, weeklyHrs, topSubject }) {
  const W = 520, H = 300;
  const cv = document.createElement("canvas");
  cv.width = W; cv.height = H;
  const ctx = cv.getContext("2d");

  const grad = ctx.createLinearGradient(0, 0, W, H);
  grad.addColorStop(0, "#050810"); grad.addColorStop(1, "#0f1628");
  ctx.fillStyle = grad; ctx.fillRect(0, 0, W, H);

  ctx.strokeStyle = "rgba(0,229,255,0.04)"; ctx.lineWidth = 1;
  for (let x = 0; x < W; x += 48) { ctx.beginPath(); ctx.moveTo(x,0); ctx.lineTo(x,H); ctx.stroke(); }
  for (let y = 0; y < H; y += 48) { ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(W,y); ctx.stroke(); }

  ctx.strokeStyle = "rgba(0,229,255,0.35)"; ctx.lineWidth = 1.5; ctx.strokeRect(1,1,W-2,H-2);

  const lg = ctx.createLinearGradient(0,0,W,0);
  lg.addColorStop(0,"#00e5ff"); lg.addColorStop(1,"#a78bfa");
  ctx.strokeStyle = lg; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(0,3); ctx.lineTo(W,3); ctx.stroke();

  ctx.font = "bold 13px monospace"; ctx.fillStyle = "#00e5ff"; ctx.fillText("ARK", 28, 36);
  ctx.fillStyle = "#e8edf8"; ctx.fillText("FOCUS", 58, 36);
  ctx.font = "9px monospace"; ctx.fillStyle = "#5a6a8a"; ctx.fillText("// study OS", 28, 52);

  const stats = [
    { label:"SESSIONS",    value:String(totalSessions),          color:"#00e5ff" },
    { label:"STREAK",      value:`${streak} 🔥`,                 color:"#ffb300" },
    { label:"THIS WEEK",   value:`${(weeklyHrs||0).toFixed(1)}h`,color:"#00ff88" },
    { label:"TOP SUBJECT", value:topSubject || "—",              color:"#a78bfa" },
  ];
  stats.forEach((s, i) => {
    const x = 28 + (i%2)*250, y = i < 2 ? 105 : 185;
    ctx.font = "9px monospace"; ctx.fillStyle = "#5a6a8a"; ctx.fillText(s.label, x, y);
    ctx.font = `bold ${i===3?18:28}px monospace`; ctx.fillStyle = s.color;
    ctx.fillText(String(s.value).slice(0,12), x, y+28);
  });

  ctx.strokeStyle = "rgba(0,229,255,0.5)"; ctx.lineWidth = 2;
  [[W-20,10,W-10,10],[W-10,10,W-10,20],[W-20,H-10,W-10,H-10],[W-10,H-20,W-10,H-10]]
    .forEach(([x1,y1,x2,y2]) => { ctx.beginPath(); ctx.moveTo(x1,y1); ctx.lineTo(x2,y2); ctx.stroke(); });

  ctx.font = "8px monospace"; ctx.fillStyle = "rgba(90,106,138,0.7)";
  ctx.fillText("Arkmaester · arkmaester.app · arkmaester.app", 28, H - 16);

  cv.toBlob((blob) => downloadBlob(blob, "arkmaester-streak-card.png"), "image/png");
}

// ── Confetti utility ──────────────────────────────────────────────────────
export function fireConfetti(opts = {}) {
  const canvas = document.getElementById("confetti-canvas");
  if (!canvas) return;
  const ctx = canvas.getContext("2d");
  canvas.width = window.innerWidth; canvas.height = window.innerHeight;
  const count  = opts.count || 55;
  const colors = ["#00e5ff","#00ff88","#ffb300","#a78bfa","#ff6b9d","#fff"];
  const particles = Array.from({ length:count }, () => ({
    x: Math.random()*canvas.width, y: -10,
    w: 6+Math.random()*8, h: 8+Math.random()*12,
    color: colors[Math.floor(Math.random()*colors.length)],
    rot: Math.random()*360, rotV: (Math.random()-0.5)*8,
    vx: (Math.random()-0.5)*4, vy: 2+Math.random()*4, alpha: 1,
  }));
  let af;
  function draw() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    let alive = false;
    particles.forEach((p) => {
      p.x += p.vx; p.y += p.vy; p.rot += p.rotV; p.alpha -= 0.008;
      if (p.alpha > 0) alive = true;
      ctx.save(); ctx.globalAlpha = Math.max(0, p.alpha);
      ctx.translate(p.x, p.y); ctx.rotate((p.rot*Math.PI)/180);
      ctx.fillStyle = p.color; ctx.fillRect(-p.w/2, -p.h/2, p.w, p.h);
      ctx.restore();
    });
    if (alive) af = requestAnimationFrame(draw);
    else ctx.clearRect(0,0,canvas.width,canvas.height);
  }
  cancelAnimationFrame(af); draw();
}

// ── Internal helper ───────────────────────────────────────────────────────
function downloadBlob(blob, filename) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
}
